/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import javax.swing.JOptionPane;
import logica.Usuario;

/**
 *
 * @author cris
 */
public class TablaSolicitud extends javax.swing.JFrame {

    /**
     * Creates new form TablaSolicitud
     */
    public TablaSolicitud() {
        initComponents();
        this.setLocationRelativeTo(null); // centra el frame en la pantalla
        this.setResizable(false);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaSolicitud = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(797, 499));
        setMinimumSize(new java.awt.Dimension(797, 499));
        setPreferredSize(new java.awt.Dimension(797, 499));
        getContentPane().setLayout(null);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(600, 240, 130, 40);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText("Solicitud de Usuarios");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 0, 340, 70);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 150, 130, 40);

        jtTablaSolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Usuario", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(jtTablaSolicitud);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 550, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoAdmin.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        this.dispose();//destruir ventana anterior
        new frameAdmin().setVisible(true); // abrir ventana de admin
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        //aqui se toman los datos de la fila seleccionada para crear la lista de los usuarios que podran jugar
        int filaSelect = jtTablaSolicitud.getSelectedRow();
        
        if (filaSelect == -1) {
            
           JOptionPane.showMessageDialog(this, "Seleccione Usuario Primero", "AVISO", 1);
            
        }
        else{
            System.out.println("filaSelect "+filaSelect);
            //se envia a la lista de aceptados 
            Usuario usuario = new Usuario(jtTablaSolicitud.getValueAt(filaSelect, 0).toString(), jtTablaSolicitud.getValueAt(filaSelect, 1).toString(), "0", "0", "1");
            viborita_serial.Viborita_Serial.ListaAceptados.add(usuario);
            JOptionPane.showMessageDialog(this, "Usuario Aceptado Exitosamente", "AVISO", 1);
            
            viborita_serial.Viborita_Serial.listaSolicitudes.remove(filaSelect);//elimina de la lista de solicitudes
            mostrar();
            
            
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtTablaSolicitud;
    // End of variables declaration//GEN-END:variables


public void mostrar(){
    
    //creacion de la matriz para mostrar las filas
    String matriz[][]=new String[viborita_serial.Viborita_Serial.listaSolicitudes.size()][2];
    
    for (int i = 0; i < viborita_serial.Viborita_Serial.listaSolicitudes.size(); i++) {
        
        matriz[i][0]= viborita_serial.Viborita_Serial.listaSolicitudes.get(i).getUsuario();
        matriz[i][1]= viborita_serial.Viborita_Serial.listaSolicitudes.get(i).getContraseña();
        
    }
    
    
    jtTablaSolicitud.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Usuario", "Contraseña"
            }
        )); 
}

}
